---
namespace: 'r_pufky'
name: 'data'
version: '3.0.5'
readme: 'README.md'
authors:
  - 'Robert Pufky <rpufky@gmail.com> (https://github.com/r-pufky)'
description: >
  Data annotations. Provide high-resolution, data-centric processing for roles
  addressing many of the shortcomings of argument spec.
license_file: 'LICENSE'
tags:
  - 'data'
  - 'annotation'
  - 'tools'
dependencies: {}

repository: 'https://github.com/r-pufky/ansible_collection_data'
documentation: 'https://r-pufky.github.io/ansible_collection_docs'
homepage: 'https://github.com/r-pufky/ansible_collection_data'
issues: 'https://github.com/r-pufky/ansible_collection_data/issues'

build_ignore:
  - '*molecule/*'  # Do not include molecule testing in release.
  - 'ansible.env'  # Development ansible environment.
  - '.ansible'  # Ansible collection cache for role testing.
  - '.vscode'  # VSCodium settings.
  - 'TODO.md'  # Development staging todo messages.
  - 'COMMIT.md'  # Development staging commit messages.
  - '*docs/*'  # Development docs are a separate repo and not end user.
